[WIP] Integration of all EOS-S3 related changes/bugfixes
SymbiFlow/f4pga-arch-defs pull request #2346
Opened 2021-12-14 16:11 UTC by mkurc-ant

This PR is intended to upstream all EOS-S3 related development which happened in the QuickLogic fork.

2021-12-14 17:50 UTC, mithro requested changes
This is a massive pull request that is almost impossible to review.

2021-12-14 17:50 UTC, mithro commented on quicklogic/common/toolchain_wrappers/symbiflow_fasm2bels
> +#!/bin/bash
We shouldn't be writing long shell scripts like this.

2021-12-14 17:50 UTC, mithro commented on quicklogic/pp3/tests/design_flow/CMakeLists.txt
> +add_subdirectory(IR_Remote)
```suggestion
add_subdirectory(ir_remote)
```

2021-12-14 17:50 UTC, mithro commented on utils/yosys_fixup_cell_names.py
> +#!/usr/bin/env python3
This script feels wrong. Why is it needed?

2021-12-14 17:50 UTC, mithro commented on utils/vpr_fixup_post_synth.py
> +def merge_verilog_ports(code):
Why is this needed?

2021-12-14 17:50 UTC, mithro commented on utils/report_timing.py
> +import argparse
Missing documentation / license / etc...

2021-12-15 08:27 UTC, mkurc-ant commented
@mithro Yes... I'm aware that this PR is far from mergable but issuing a PR was the only way to trigger Kokoro CI to test the changes. It exploded anyway.

2022-06-21 12:40 UTC, closed without merging